/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SorteioRequest } from '../../models/sorteio-request';
import { SorteioResponse } from '../../models/sorteio-response';

export interface SortearTimes$Params {
  peladaId: number;
      body: SorteioRequest
}

export function sortearTimes(http: HttpClient, rootUrl: string, params: SortearTimes$Params, context?: HttpContext): Observable<StrictHttpResponse<SorteioResponse>> {
  const rb = new RequestBuilder(rootUrl, sortearTimes.PATH, 'post');
  if (params) {
    rb.path('peladaId', params.peladaId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SorteioResponse>;
    })
  );
}

sortearTimes.PATH = '/api/peladas/{peladaId}/sorteio';
