/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UsuarioRequest } from '../models/usuario-request';

/**
 * Perfil do jogador mais a senha de acesso
 */
export interface CadastroRequest {

  /**
   * Senha de 8 a 72 caracteres; o teto é o limite do BCrypt
   */
  senha: string;

  /**
   * Dados do perfil, idênticos aos da edição
   */
  usuario: UsuarioRequest;
}
