/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RankingAtributoResponse } from '../models/ranking-atributo-response';
export interface DestaqueResponse {
  atributo: 'GOL' | 'DEFESA_DIFICIL' | 'ASSISTENCIA' | 'DEFESA' | 'DESARME';
  descricao: string;
  peso: number;
  ranking: Array<RankingAtributoResponse>;
}
