/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Contrato único de erro da API: vale tanto para o que o GlobalExceptionHandler trata quanto para os 401 e 403 barrados no filtro de segurança
 */
export interface ErroResponse {

  /**
   * Preenchido só nos 400 de validação: campo para mensagem
   */
  campos?: {
[key: string]: string;
};

  /**
   * Categoria do erro
   */
  erro: string;

  /**
   * Explicação legível
   */
  mensagem: string;

  /**
   * Código HTTP
   */
  status: number;

  /**
   * Momento em que o erro ocorreu
   */
  timestamp: string;
}
