/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Súmula de um jogador. Todo número omitido vale zero.
 */
export interface EstatisticaRequest {

  /**
   * Assistências
   */
  assistencias?: number;

  /**
   * Defesas; só para quem jogou no gol
   */
  defesas?: number;

  /**
   * Defesas difíceis; subconjunto das defesas, nunca maior que elas
   */
  defesasDificeis?: number;

  /**
   * Desarmes
   */
  desarmes?: number;

  /**
   * Gols marcados
   */
  gols?: number;

  /**
   * Posição efetivamente jogada. Omitida, vale a do cadastro — serve para o jogador de linha que foi para o gol.
   */
  posicaoJogada?: 'GOLEIRO' | 'ALA' | 'FIXO' | 'PIVO' | 'AMADOR';
}
