/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PontuacaoAtributoResponse } from '../models/pontuacao-atributo-response';
import { UsuarioResumoResponse } from '../models/usuario-resumo-response';
export interface EstatisticaResponse {
  assistencias?: number;
  atualizadaEm?: string;
  defesas?: number;
  defesasDificeis?: number;
  desarmes?: number;
  detalhamento?: Array<PontuacaoAtributoResponse>;
  goleiro?: boolean;
  gols?: number;
  id?: number;
  jogador?: UsuarioResumoResponse;
  peladaId?: number;
  pontuacao?: number;
  posicaoJogada?: 'GOLEIRO' | 'ALA' | 'FIXO' | 'PIVO' | 'AMADOR';
  posicaoJogadaDescricao?: string;
  registradaEm?: string;
}
