/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UsuarioResumoResponse } from '../models/usuario-resumo-response';
export interface JogadorSorteadoResponse {
  goleiro?: boolean;
  jogador?: UsuarioResumoResponse;
}
