/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Credenciais de acesso
 */
export interface LoginRequest {

  /**
   * E-mail do cadastro
   */
  email: string;

  /**
   * Senha do cadastro
   */
  senha: string;
}
