/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PeladaResumoResponse } from '../models/pelada-resumo-response';
export interface PageResponsePeladaResumoResponse {
  conteudo: Array<PeladaResumoResponse>;
  pagina: number;
  primeira: boolean;
  tamanho: number;
  totalElementos: number;
  totalPaginas: number;
  ultima: boolean;
}
