/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UsuarioResponse } from '../models/usuario-response';
export interface PageResponseUsuarioResponse {
  conteudo: Array<UsuarioResponse>;
  pagina: number;
  primeira: boolean;
  tamanho: number;
  totalElementos: number;
  totalPaginas: number;
  ultima: boolean;
}
