/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UsuarioResumoResponse } from '../models/usuario-resumo-response';
export interface ParticipanteResponse {
  dataInscricao: string;
  participacaoId: number;
  status: 'CONVIDADO' | 'CONFIRMADO' | 'RECUSADO' | 'LISTA_DE_ESPERA';
  statusDescricao: string;
  usuario: UsuarioResumoResponse;
}
