/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Inclusão de um jogador na escalação
 */
export interface ParticipacaoRequest {

  /**
   * CONVIDADO quando o organizador convida, CONFIRMADO quando o próprio jogador entra. Omitido, vale CONFIRMADO.
   */
  status?: 'CONVIDADO' | 'CONFIRMADO' | 'RECUSADO' | 'LISTA_DE_ESPERA';

  /**
   * Id do jogador a escalar
   */
  usuarioId: number;
}
