/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Agendamento de uma pelada. O organizador não vem no corpo: é sempre o usuário do token.
 */
export interface PeladaRequest {

  /**
   * Cidade
   */
  cidade: string;

  /**
   * Data do jogo; não pode estar no passado
   */
  data: string;

  /**
   * Observações para os convidados
   */
  descricao?: string;

  /**
   * Endereço do local
   */
  endereco: string;

  /**
   * Sigla do estado, com 2 letras
   */
  estado: string;

  /**
   * Horário de término; precisa ser posterior ao início
   */
  horaFim: string;

  /**
   * Horário de início
   */
  horaInicio: string;

  /**
   * Nome da quadra ou do campo
   */
  localNome: string;

  /**
   * Limite de vagas; a partir daí a escalação vira lista de espera
   */
  maxParticipantes: number;

  /**
   * Nome da pelada
   */
  nome: string;

  /**
   * Tipo de campo
   */
  tipoCampo: 'FUTSAL' | 'SOCIETY';

  /**
   * Rateio por jogador, em reais
   */
  valorPorJogador?: number;
}
