/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PontuacaoAtributoResponse {
  atributo: 'GOL' | 'DEFESA_DIFICIL' | 'ASSISTENCIA' | 'DEFESA' | 'DESARME';
  descricao: string;
  peso: number;
  pontos: number;
  quantidade: number;
}
