/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PontuacaoAtributoResponse } from '../models/pontuacao-atributo-response';
import { UsuarioResumoResponse } from '../models/usuario-resumo-response';
export interface RankingResponse {
  assistencias: number;
  defesas: number;
  defesasDificeis: number;
  desarmes: number;
  detalhamento: Array<PontuacaoAtributoResponse>;
  gols: number;
  jogador: UsuarioResumoResponse;
  jogos: number;
  mediaPorJogo: number;
  pontuacao: number;
  posicao: number;
}
