/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UsuarioResumoResponse } from '../models/usuario-resumo-response';
export interface RankingAtributoResponse {
  jogador: UsuarioResumoResponse;
  jogos: number;
  pontos: number;
  posicao: number;
  total: number;
}
