/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Critério do sorteio: informe quantidadeTimes OU jogadoresPorTime, nunca os dois. O outro valor é deduzido dos confirmados.
 */
export interface SorteioRequest {

  /**
   * Quantos jogadores por time
   */
  jogadoresPorTime?: number;

  /**
   * Quantos times formar
   */
  quantidadeTimes?: number;

  /**
   * Semente do sorteio. A mesma semente reproduz exatamente a mesma divisão, útil para refazer ou conferir um sorteio já combinado.
   */
  semente?: number;
}
