/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Nova situação da pelada
 */
export interface StatusPeladaRequest {

  /**
   * Situação de destino, respeitando as transições permitidas
   */
  status: 'AGENDADA' | 'CONFIRMADA' | 'EM_ANDAMENTO' | 'FINALIZADA' | 'CANCELADA';
}
