/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Nova situação da participação de um jogador
 */
export interface StatusParticipacaoRequest {

  /**
   * Só CONFIRMADO ocupa vaga. Sair de CONFIRMADO libera a vaga e promove o primeiro da lista de espera.
   */
  status: 'CONVIDADO' | 'CONFIRMADO' | 'RECUSADO' | 'LISTA_DE_ESPERA';
}
