/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { JogadorSorteadoResponse } from '../models/jogador-sorteado-response';
export interface TimeSorteadoResponse {
  jogadores: Array<JogadorSorteadoResponse>;
  mediaEstrelas: number;
  nome: string;
  quantidadeJogadores: number;
  temGoleiro: boolean;
  totalEstrelas: number;
}
