/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UsuarioResumoResponse {
  estrelas?: number;
  id?: number;
  nickname?: string;
  nomeCompleto?: string;
  posicao?: 'GOLEIRO' | 'ALA' | 'FIXO' | 'PIVO' | 'AMADOR';
  posicaoDescricao?: string;
}
