/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UsuarioResponse {
  descricao?: string;
  email?: string;
  estrelas?: number;
  id?: number;
  idade?: number;
  nacionalidade?: string;
  nickname?: string;
  nomeCompleto?: string;
  numeroCelular?: string;
  posicao?: 'GOLEIRO' | 'ALA' | 'FIXO' | 'PIVO' | 'AMADOR';
  posicaoDescricao?: string;
}
