/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Perfil de jogador
 */
export interface UsuarioRequest {

  /**
   * Texto livre de apresentação
   */
  descricao?: string;

  /**
   * E-mail único, usado também no login
   */
  email: string;

  /**
   * Nível técnico de 1 a 5, de meia em meia estrela. Omitido, o jogador entra como mediano (3). É o peso usado no sorteio.
   */
  estrelas?: number;

  /**
   * Idade em anos
   */
  idade: number;

  /**
   * Nacionalidade
   */
  nacionalidade: string;

  /**
   * Apelido único dentro da liga
   */
  nickname: string;

  /**
   * Nome completo
   */
  nomeCompleto: string;

  /**
   * Celular com DDD
   */
  numeroCelular: string;

  /**
   * Posição em quadra
   */
  posicao: 'GOLEIRO' | 'ALA' | 'FIXO' | 'PIVO' | 'AMADOR';
}
