/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CadastroRequest } from './models/cadastro-request';
export type { DestaqueResponse } from './models/destaque-response';
export type { ErroResponse } from './models/erro-response';
export type { EstatisticaRequest } from './models/estatistica-request';
export type { EstatisticaResponse } from './models/estatistica-response';
export type { JogadorSorteadoResponse } from './models/jogador-sorteado-response';
export type { LoginRequest } from './models/login-request';
export type { PageResponsePeladaResumoResponse } from './models/page-response-pelada-resumo-response';
export type { PageResponseUsuarioResponse } from './models/page-response-usuario-response';
export type { ParticipacaoRequest } from './models/participacao-request';
export type { ParticipanteResponse } from './models/participante-response';
export type { PeladaRequest } from './models/pelada-request';
export type { PeladaResponse } from './models/pelada-response';
export type { PeladaResumoResponse } from './models/pelada-resumo-response';
export type { PontuacaoAtributoResponse } from './models/pontuacao-atributo-response';
export type { RankingAtributoResponse } from './models/ranking-atributo-response';
export type { RankingResponse } from './models/ranking-response';
export type { SorteioRequest } from './models/sorteio-request';
export type { SorteioResponse } from './models/sorteio-response';
export type { StatusParticipacaoRequest } from './models/status-participacao-request';
export type { StatusPeladaRequest } from './models/status-pelada-request';
export type { TimeSorteadoResponse } from './models/time-sorteado-response';
export type { TokenResponse } from './models/token-response';
export type { UsuarioRequest } from './models/usuario-request';
export type { UsuarioResponse } from './models/usuario-response';
export type { UsuarioResumoResponse } from './models/usuario-resumo-response';
