/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ParticipanteResponse } from '../../models/participante-response';
import { StatusParticipacaoRequest } from '../../models/status-participacao-request';

export interface AlterarStatusParticipacao$Params {
  id: number;
  usuarioId: number;
      body: StatusParticipacaoRequest
}

export function alterarStatusParticipacao(http: HttpClient, rootUrl: string, params: AlterarStatusParticipacao$Params, context?: HttpContext): Observable<StrictHttpResponse<ParticipanteResponse>> {
  const rb = new RequestBuilder(rootUrl, alterarStatusParticipacao.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('usuarioId', params.usuarioId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ParticipanteResponse>;
    })
  );
}

alterarStatusParticipacao.PATH = '/api/peladas/{id}/participantes/{usuarioId}';
