/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PeladaResponse } from '../../models/pelada-response';

export interface BuscarPelada$Params {
  id: number;
}

export function buscarPelada(http: HttpClient, rootUrl: string, params: BuscarPelada$Params, context?: HttpContext): Observable<StrictHttpResponse<PeladaResponse>> {
  const rb = new RequestBuilder(rootUrl, buscarPelada.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PeladaResponse>;
    })
  );
}

buscarPelada.PATH = '/api/peladas/{id}';
