/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PeladaRequest } from '../../models/pelada-request';
import { PeladaResponse } from '../../models/pelada-response';

export interface CriarPelada$Params {
      body: PeladaRequest
}

export function criarPelada(http: HttpClient, rootUrl: string, params: CriarPelada$Params, context?: HttpContext): Observable<StrictHttpResponse<PeladaResponse>> {
  const rb = new RequestBuilder(rootUrl, criarPelada.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PeladaResponse>;
    })
  );
}

criarPelada.PATH = '/api/peladas';
