/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponsePeladaResumoResponse } from '../../models/page-response-pelada-resumo-response';

export interface ListarPeladas$Params {

/**
 * Situação da pelada
 */
  status?: 'AGENDADA' | 'CONFIRMADA' | 'EM_ANDAMENTO' | 'FINALIZADA' | 'CANCELADA';

/**
 * Tipo de campo
 */
  tipoCampo?: 'FUTSAL' | 'SOCIETY';

/**
 * Cidade; busca parcial, sem diferenciar maiúsculas
 */
  cidade?: string;

/**
 * Peladas a partir desta data (ISO)
 */
  dataInicial?: string;

/**
 * Peladas até esta data (ISO)
 */
  dataFinal?: string;

/**
 * Só as peladas organizadas por este jogador
 */
  organizadorId?: number;

/**
 * Só as peladas em que este jogador está escalado
 */
  participanteId?: number;

/**
 * Zero-based page index (0..N)
 */
  page?: number;

/**
 * The size of the page to be returned
 */
  size?: number;

/**
 * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 */
  sort?: Array<string>;
}

export function listarPeladas(http: HttpClient, rootUrl: string, params?: ListarPeladas$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponsePeladaResumoResponse>> {
  const rb = new RequestBuilder(rootUrl, listarPeladas.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('tipoCampo', params.tipoCampo, {});
    rb.query('cidade', params.cidade, {});
    rb.query('dataInicial', params.dataInicial, {});
    rb.query('dataFinal', params.dataFinal, {});
    rb.query('organizadorId', params.organizadorId, {});
    rb.query('participanteId', params.participanteId, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sort', params.sort, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponsePeladaResumoResponse>;
    })
  );
}

listarPeladas.PATH = '/api/peladas';
