/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DestaqueResponse } from '../../models/destaque-response';

export interface Destaques$Params {

/**
 * Restringe os destaques a uma pelada
 */
  peladaId?: number;

/**
 * Quantos destaques por atributo
 */
  limite?: number;
}

export function destaques(http: HttpClient, rootUrl: string, params?: Destaques$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DestaqueResponse>>> {
  const rb = new RequestBuilder(rootUrl, destaques.PATH, 'get');
  if (params) {
    rb.query('peladaId', params.peladaId, {});
    rb.query('limite', params.limite, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DestaqueResponse>>;
    })
  );
}

destaques.PATH = '/api/ranking/destaques';
