/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RankingResponse } from '../../models/ranking-response';

export interface RankingGeral$Params {

/**
 * Restringe a classificação a uma pelada
 */
  peladaId?: number;

/**
 * Traz apenas os N primeiros colocados
 */
  limite?: number;
}

export function rankingGeral(http: HttpClient, rootUrl: string, params?: RankingGeral$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RankingResponse>>> {
  const rb = new RequestBuilder(rootUrl, rankingGeral.PATH, 'get');
  if (params) {
    rb.query('peladaId', params.peladaId, {});
    rb.query('limite', params.limite, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RankingResponse>>;
    })
  );
}

rankingGeral.PATH = '/api/ranking';
