/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RankingAtributoResponse } from '../../models/ranking-atributo-response';

export interface RankingPorAtributo$Params {

/**
 * Atributo da tabela de pontuação
 */
  atributo: 'GOL' | 'DEFESA_DIFICIL' | 'ASSISTENCIA' | 'DEFESA' | 'DESARME';

/**
 * Restringe o ranking a uma pelada
 */
  peladaId?: number;

/**
 * Traz apenas os N primeiros colocados
 */
  limite?: number;
}

export function rankingPorAtributo(http: HttpClient, rootUrl: string, params: RankingPorAtributo$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RankingAtributoResponse>>> {
  const rb = new RequestBuilder(rootUrl, rankingPorAtributo.PATH, 'get');
  if (params) {
    rb.path('atributo', params.atributo, {});
    rb.query('peladaId', params.peladaId, {});
    rb.query('limite', params.limite, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RankingAtributoResponse>>;
    })
  );
}

rankingPorAtributo.PATH = '/api/ranking/atributos/{atributo}';
