/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UsuarioResponse } from '../../models/usuario-response';

export interface BuscarUsuario$Params {
  id: number;
}

export function buscarUsuario(http: HttpClient, rootUrl: string, params: BuscarUsuario$Params, context?: HttpContext): Observable<StrictHttpResponse<UsuarioResponse>> {
  const rb = new RequestBuilder(rootUrl, buscarUsuario.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UsuarioResponse>;
    })
  );
}

buscarUsuario.PATH = '/api/usuarios/{id}';
