/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseUsuarioResponse } from '../../models/page-response-usuario-response';

export interface ListarUsuarios$Params {

/**
 * Posição em quadra
 */
  posicao?: 'GOLEIRO' | 'ALA' | 'FIXO' | 'PIVO' | 'AMADOR';

/**
 * Busca parcial por nome completo ou nickname
 */
  busca?: string;

/**
 * Nacionalidade do jogador
 */
  nacionalidade?: string;

/**
 * Zero-based page index (0..N)
 */
  page?: number;

/**
 * The size of the page to be returned
 */
  size?: number;

/**
 * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 */
  sort?: Array<string>;
}

export function listarUsuarios(http: HttpClient, rootUrl: string, params?: ListarUsuarios$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseUsuarioResponse>> {
  const rb = new RequestBuilder(rootUrl, listarUsuarios.PATH, 'get');
  if (params) {
    rb.query('posicao', params.posicao, {});
    rb.query('busca', params.busca, {});
    rb.query('nacionalidade', params.nacionalidade, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sort', params.sort, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseUsuarioResponse>;
    })
  );
}

listarUsuarios.PATH = '/api/usuarios';
