/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EstatisticaResponse } from '../../models/estatistica-response';

export interface BuscarEstatistica$Params {
  peladaId: number;
  usuarioId: number;
}

export function buscarEstatistica(http: HttpClient, rootUrl: string, params: BuscarEstatistica$Params, context?: HttpContext): Observable<StrictHttpResponse<EstatisticaResponse>> {
  const rb = new RequestBuilder(rootUrl, buscarEstatistica.PATH, 'get');
  if (params) {
    rb.path('peladaId', params.peladaId, {});
    rb.path('usuarioId', params.usuarioId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EstatisticaResponse>;
    })
  );
}

buscarEstatistica.PATH = '/api/peladas/{peladaId}/participantes/{usuarioId}/estatistica';
