/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EstatisticaResponse } from '../../models/estatistica-response';

export interface ListarEstatisticas$Params {
  peladaId: number;
}

export function listarEstatisticas(http: HttpClient, rootUrl: string, params: ListarEstatisticas$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EstatisticaResponse>>> {
  const rb = new RequestBuilder(rootUrl, listarEstatisticas.PATH, 'get');
  if (params) {
    rb.path('peladaId', params.peladaId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<EstatisticaResponse>>;
    })
  );
}

listarEstatisticas.PATH = '/api/peladas/{peladaId}/estatisticas';
