/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface RemoverEstatistica$Params {
  peladaId: number;
  usuarioId: number;
}

export function removerEstatistica(http: HttpClient, rootUrl: string, params: RemoverEstatistica$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, removerEstatistica.PATH, 'delete');
  if (params) {
    rb.path('peladaId', params.peladaId, {});
    rb.path('usuarioId', params.usuarioId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

removerEstatistica.PATH = '/api/peladas/{peladaId}/participantes/{usuarioId}/estatistica';
